# Generated by Django 5.2.2 on 2025-06-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facilities',
            new_name='Facility',
        ),
    ]
